apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJaV3d0TnpZNloyaHdYMmxDYzBjMmRrOTNVMEZRVERFNE9XUm9lRzFzYlVWME1UQmhSRWxhWVRKbmNFTTJTZz09IgogICAgICAgIH0KICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson
